language: python
python:
  - 2.6
  - 2.7
env:
  - PLONE_VERSION=4.0
  - PLONE_VERSION=4.1
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3 QA=true
matrix:
  allow_failures:
    - python: 2.6
      env: PLONE_VERSION=4.0
  exclude:
    - python: 2.7
      env: PLONE_VERSION=4.0
    - python: 2.7
      env: PLONE_VERSION=4.1
    - python: 2.6
      env: PLONE_VERSION=4.2
    - python: 2.6
      env: PLONE_VERSION=4.3 QA=true
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - make install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: make tests
after_success: make qa
notifications:
  irc: irc.freenode.org#simplesconsultoria
